package de.othr.event_hub.service;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;

import de.othr.event_hub.config.AccountUserDetails;
import de.othr.event_hub.model.User;
import de.othr.event_hub.repository.UserRepository;

@Service
public class AccountUserDetailsService implements UserDetailsService {
    @Autowired
    UserRepository userRepository;

    public AccountUserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
        // TODO autogenerated method stub
        Optional<User> user = userRepository.findUserByUsername(username);

        return new AccountUserDetails(user.orElseThrow(() -> new UsernameNotFoundException("Not found: " + username)));
    }
}
